---
title: "leafletplugins Examples"
output:
  html_document:
    toc_float: false
---



## Search toolbar

Search for marker by lable or popup

```{r search_toolbar}

library(leafletplugins)

data(quakes)

map <- leaflet(data = quakes[1:20,]) %>%
	addTiles() %>%
	addMarkers(~long, ~lat, popup = ~as.character(mag),
			group = 'marker', label = ~as.character(mag))
			
# Search by popup
map %>% 
   addSearchMarker('marker', position = 'topleft', propertyName = 'popup')

```


```{r search_label}
# Search by label
map %>% 
   addSearchMarker('marker', position = 'topleft', propertyName = 'label')

```



Search with open street map api

```{r}
leaflet(data = quakes) %>%
    addTiles() %>%
    addSearchOSM()
```


## Full screen control

```{r}
leaflet() %>%
    addTiles() %>%
    addControlFullScreen()
```


## Current GPS location

```{r}
leaflet() %>%
   addTiles() %>%
   addControlGPS()
```

## Gaode map (in Chinese)

The zoom level has to be less than 3 in Gaode map.
```{r}
leaflet() %>%
   addTileGaodeMap() %>%
   setView(lat = 37.550339, lng = 104.114129, zoom = 4)
```
